In [1]:
import numpy as np

# Initialize the matrix
result_matrix = np.array([[-1/2, -1/2], [-1/2, -1/2]])

print("Resulting Matrix:")
print(result_matrix)


Resulting Matrix:
[[-0.5 -0.5]
 [-0.5 -0.5]]


In [2]:
import numpy as np

# Initialize the matrix Uf
Uf = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1]
])

print("Oracle matrix Uf:")
print(Uf)


Oracle matrix Uf:
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


In [2]:
import numpy as np
import cirq

# Define the oracle matrix Uf
Uf = np.array([
    [1, 0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0, 1]
])

# Define the matrix -I + 2A
result_matrix = np.array([
    [-1/2, 1/2, 1/2, 1/2],
    [1/2, -1/2, 1/2, 1/2],
    [1/2, 1/2, -1/2, 1/2],
    [1/2, 1/2, 1/2, -1/2]
])

# Define the number of qubits
n = 3  # Assuming 3 qubits for demonstration purposes

# Initialize the circuit
circuit = cirq.Circuit()


# Step 1: Apply H⊗n
circuit.append(cirq.H.on_each(*cirq.LineQubit.range(n-1)))
circuit.append(cirq.X(cirq.LineQubit(n - 1)))
# Step 2: Repeat √2^n times
sqrt_n = int(np.sqrt(2 ** n))+1
for _ in range(sqrt_n):
    # Step 3a: Apply the phase inversion operation: Uf (I ⊗ H)
 
    circuit.append(cirq.H(cirq.LineQubit(n - 1)))
    circuit.append(cirq.MatrixGate(Uf).on(*cirq.LineQubit.range(n)))
   
    
    # Step 3b: Apply the inversion about the mean operation: -I + 2A
    circuit.append(cirq.MatrixGate(result_matrix).on(*cirq.LineQubit.range(n-1)))

# Step 4: Measure the qubits
circuit.append(cirq.measure(*cirq.LineQubit.range(2), key='result'))

# Print the circuit
print("Grover's Algorithm Circuit:")
print(circuit)

# Simulate the circuit
simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=3)

# Extract measurement results from the result object
measurement_result = result.measurements['result'][0]

# Print the measurement result
print("\nMeasurement Result:")
print(measurement_result)

final_state_vector = simulator.simulate(circuit).final_state_vector
print(final_state_vector)


Grover's Algorithm Circuit:
              ┌               ┐                           ┌               ┐                           ┌               ┐
              │1 0 0 0 0 0 0 0│                           │1 0 0 0 0 0 0 0│                           │1 0 0 0 0 0 0 0│
              │0 1 0 0 0 0 0 0│   ┌                   ┐   │0 1 0 0 0 0 0 0│   ┌                   ┐   │0 1 0 0 0 0 0 0│   ┌                   ┐
              │0 0 1 0 0 0 0 0│   │-0.5  0.5  0.5  0.5│   │0 0 1 0 0 0 0 0│   │-0.5  0.5  0.5  0.5│   │0 0 1 0 0 0 0 0│   │-0.5  0.5  0.5  0.5│
0: ───H───────│0 0 0 1 0 0 0 0│───│ 0.5 -0.5  0.5  0.5│───│0 0 0 1 0 0 0 0│───│ 0.5 -0.5  0.5  0.5│───│0 0 0 1 0 0 0 0│───│ 0.5 -0.5  0.5  0.5│───M('result')───
              │0 0 0 0 0 1 0 0│   │ 0.5  0.5 -0.5  0.5│   │0 0 0 0 0 1 0 0│   │ 0.5  0.5 -0.5  0.5│   │0 0 0 0 0 1 0 0│   │ 0.5  0.5 -0.5  0.5│   │
              │0 0 0 0 1 0 0 0│   │ 0.5  0.5  0.5 -0.5│   │0 0 0 0 1 0 0 0│   │ 0.5  0.5  0.5 -0.5│   │0 0 0 0 1 0 0 0│   │ 0.5  0.5  0