In [2]:
import numpy as np

# Define the time-domain signal x[n] with N = 4 samples
N = 4
n = np.arange(N)

# Given signal: x[n] = 5 + 3cos(2π * (1/N) * n-90) + 3cos(2π * (2/N) * n)
x = 5 + 3 * np.cos(2 * np.pi * 1 * n / N-(np.pi/2)) + 3 * np.cos(4 * np.pi * n / N)


# Compute DFT using numpy's FFT function
X = np.fft.fft(x)

# Compute IDFT using numpy's IFFT function
x_reconstructed = np.fft.ifft(X).real  # Taking real part to remove numerical errors

# Display results
x, X, x_reconstructed


(array([ 8.,  5.,  8., -1.]),
 array([20.+0.j,  0.-6.j, 12.+0.j,  0.+6.j]),
 array([ 8.,  5.,  8., -1.]))